ProductWeb/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ProductWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProductWeb/Controllers/MaterialController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Product.DomainObjects.Models;
using Product.Services;

namespace ProductWeb.Controllers
{
    public class MaterialController : Controller
    {
        private readonly IMaterialService _materialService;

        public MaterialController(IMaterialService materialService)
        {
            _materialService = materialService;
        }

        // GET
        public ActionResult Index()
        {
            return View(_materialService.GetAll());
        }

        // GET
        public ActionResult View(Int32 id)
        {
            ViewBag.SelectedMaterialId = id;
            //return View(_materialService.GetById(id));
            return View(_materialService.GetAllWithProducts().Where(mm=>mm.Materials.Count()>0).ToList());
        }

      

        // GET: RateReviews/Create
        public ActionResult CreateMaterial()
        {
            
            return View();
        }

        // POST: Material/CreateMaterial, This will create the Material
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMaterial([Bind(Include = "Name,Cost")] MaterialModel material)
        {
            if (ModelState.IsValid)
            {

                _materialService.Create(material.Name, material.Cost);
                return RedirectToAction("Index");
            }

            
            return View(material);
        }


       
        public void Merge(string materialIdToKeep, string materialIdToDelete)
        {
            ViewBag.Message = "";
            int[] listOf = { 0 };
            if (!string.IsNullOrEmpty(materialIdToDelete))
            {
                listOf = materialIdToDelete.Split(',').Select(int.Parse).ToArray();
            }
            
            _materialService.Merge(Convert.ToInt32( materialIdToKeep), listOf);

            ViewBag.Message = "Merging has done successfully, check ProdcutMaterials table for Quantity update.";

            //RedirectToAction("Index", "Material");
        }

    }
}

ProductWeb/Controllers/ProductController.cs
using System;
using System.Web.Mvc;
using Product.Services;

namespace ProductWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        // GET
        public ActionResult Index()
        {
            return View(_productService.GetAll());
        }
        
        // GET
        public ActionResult View(Int32 id)
        {
            return View(_productService.GetById(id));
        }
    }
}

ProductWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProductWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProductWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET  @Html.ActionLink("Materials", "Index", "Material")</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ProductWeb/Views/Material/CreateMaterial.cshtml
@model Product.DomainObjects.Models.MaterialModel

@{
    ViewBag.Title = "Create Material";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Material</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Material</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.MaterialId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaterialId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaterialId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CreateMaterial" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProductWeb/Views/Material/Index.cshtml
@model System.Collections.Generic.IList<Product.DomainObjects.Models.MaterialModel>

@{
    ViewBag.Title = "Materials";
}

<h2>Materials</h2>
<p>
    @Html.ActionLink("Create New Material", "CreateMaterial")
</p>
<h2>@ViewBag.Message</h2>
<table class="table table-striped">
    
    <tr>
        <td>
            ID
        </td>
        <th>
            Material
        </th>
        <th>
            Cost
        </th>
        <th>
            @*actions*@
        </th>
    </tr>
    @foreach (var m in Model)
    {
        <tr>
            <td>
                @m.MaterialId
            </td>
            <td>
                @m.Name
            </td>
            <td>
                @m.Cost
            </td>
            <td>
                @Html.ActionLink("view", "View", new {id = m.MaterialId})
            </td>
        </tr>
    }
</table>

ProductWeb/Views/Material/View.cshtml
@*@model Product.DomainObjects.Models.MaterialModel*@
@model IEnumerable<Product.DomainObjects.Models.MaterialModel>
@{
    ViewBag.Title = "Material";
    var id = 1;
}

@*<p><input type="button" value="Back" onclick="window.history.back()" /></p>*@

<p>@Html.ActionLink("Back", "Index")</p>

@foreach (var item in Model)
{

    if (item.MaterialId == @ViewBag.SelectedMaterialId)
    {
        id++;
        <h2>@item.Name</h2>
        <div>
            ID: $ @item.MaterialId
        </div>
        <div>
            Cost: $ @item.Cost
        </div>

        <div>Please select the Material from below which you want to merge with this Material i.e.<strong>@item.Name</strong></div>
    }
}
@if (id == 1)
{
    <div><strong>No Material is associate with the products, so no Merging allowed.</strong></div>
}
<table class="table">
    <tr>
        <th>Check</th>
        <th>Name</th>
        <th>MaterialId</th>
        <th>Cost</th>
    </tr>

    @foreach (var item in Model)
    {

        {
            if (item.MaterialId != @ViewBag.SelectedMaterialId)
            {


                <tr>

                    <td>@Html.CheckBox("isMerge", false, new { value = item.MaterialId, id = item.MaterialId })</td>
                    <td>@item.Name</td>
                    <td>@item.MaterialId</td>
                    <td>@item.Cost</td>
                </tr>
            }
        }
    }
</table>

@*<h2>@Model.Name</h2>
    <div>
        ID: $@Model.MaterialId
    </div>
    <div>
        Cost: $@Model.Cost
    </div>*@
<p>
    @if (id > 1)
    {
        <button id="merge" class="btn btn-warning">Merge</button>
    }
    else
    {
        <div><strong>No Material is associate with the products, so no Merging allowed.</strong></div>
    }
    Please implement a Merge functionality from here.
    Get the list of all other Material material
    select which you want to merge
    Merget

</p>
@*<p><input type="button" value="Back" onclick="window.history.back()" /></p>*@
<p>@Html.ActionLink("Back", "Index")</p>

@section scripts{

    <script type="text/javascript">
        $(document).ready(function () {

            $('#merge').click(function () {
                alert('Merge clicked');
                //var mergeID = $('input[name="isMerge"]:checked');
                var mergeID = $("input[name=isMerge]:checked").map(
                    function () { return this.value; }).get().join(",");

                var data = JSON.stringify({
                    'materialIdToKeep' : @ViewBag.SelectedMaterialId,
                    'materialIdToDelete' : mergeID
                });

                debugger;
                @*var url = '@Url.Action("Material", "Merge", new { materialIdToKeep = @ViewBag.SelectedMaterialId,materialIdToDelete = "neeraj" }, null)';
                url = url.replace("neeraj", mergeID)*@

                $.ajax({
                    url: '@Url.Action("Merge", "Material")',
                     data: data,
                    //data: { 'materialIdToKeep': @ViewBag.SelectedMaterialId, 'materialIdToDelete':  mergeID },
                         type: 'POST',
                        dataType: 'json',
                        contentType: 'application/json',
                        success: function(data){
                            alert("Merging has done successfully, check ProductMaterials table for Quantity update.");
                            $.post('/Material/Index/', function (result) {
                                // Do something with the result like for example inject it into
                                // some placeholder and update the DOM.
                                // This obviously assumes that your controller action returns
                                // a partial view otherwise you will break your markup
                            });
                     },
                     error: function (xhr, status, error) {
                         //TODO: There is some error will sort out latter, as of now just refreshing page to show the result
                         debugger;
                         location.reload();
                         //alert(error);
                    }

                });



                //$.ajax({
                //            type: "POST",
                //             url: url,
                //    success: function () { alert('Success'); },
                //    error: function () {alert('error')}
                //        });

            });
    });
    </script>

}

ProductWeb/Views/Product/Index.cshtml
@model System.Collections.Generic.IList<Product.DomainObjects.Models.ProductModel>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>

<table class="table table-striped">
    <tr>
        <td>
            ID
        </td>
        <th>
            Product
        </th>
        <th>
            Price
        </th>
        <th>
            @*actions*@
        </th>
    </tr>
    @foreach (var p in Model)
    {
    <tr>
        <td>
            @p.ProductId
        </td>
        <td>
            @p.Name
        </td>
        <td>
            @p.Price
        </td>
        <td>
            @Html.ActionLink("view", "View", new { id = p.ProductId })
        </td>
    </tr>
    }
</table>

ProductWeb/Views/Product/View.cshtml
@model Product.DomainObjects.Models.ProductModel

@{
    ViewBag.Title = "Product";
}

<h2>@Model.Name</h2>

<div>
    ID: $@Model.ProductId
</div>
<div>
    Price: $@Model.Price
</div>

<h3>Materials</h3>
<p>
    Materials used to create this product.
</p>
<td>
    <ul>
        @foreach (var m in Model.Materials)
        {
            <li>
                @String.Format("{0} x {1} [MaterialId = {2}]", m.Quantity, m.MaterialName, m.MaterialId)
            </li>
        }
    </ul>
</td>

ProductWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Materials", "Index", "Material")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>